import { create } from 'zustand'
import { type Property } from '../data/properties'
import { supabase } from '../lib/supabase'
import { logToGoogleSheet } from '../lib/logger'
import { useActivityStore } from './activityStore'

interface PropertyStore {
  properties: Property[]
  loading: boolean
  error: string | null
  fetchProperties: () => Promise<void>
  addProperty: (property: Omit<Property, 'id' | 'propertyCode'>) => Promise<void>
  updateProperty: (id: string, updates: Partial<Property>) => Promise<void>
  deleteProperty: (id: string) => Promise<void>
  getPropertyById: (id: string) => Property | undefined
  getPublishedProperties: () => Property[]
}

// Convert camelCase to snake_case for database
const toSnakeCase = (obj: any): any => {
  if (Array.isArray(obj)) {
    return obj.map(toSnakeCase)
  } else if (obj !== null && typeof obj === 'object') {
    return Object.keys(obj).reduce((acc, key) => {
      const snakeKey = key.replace(/([A-Z])/g, '_$1').toLowerCase()
      acc[snakeKey] = toSnakeCase(obj[key])
      return acc
    }, {} as any)
  }
  return obj
}

// Convert snake_case to camelCase for application
const toCamelCase = (obj: any): any => {
  if (Array.isArray(obj)) {
    return obj.map(toCamelCase)
  } else if (obj !== null && typeof obj === 'object') {
    const result = Object.keys(obj).reduce((acc, key) => {
      const camelKey = key.replace(/_([a-z])/g, (_, char) => char.toUpperCase())
      acc[camelKey] = toCamelCase(obj[key])
      return acc
    }, {} as any)
    // Ensure reviews exists
    if (!result.reviews) {
      result.reviews = []
    }
    // Ensure videos exists
    if (!result.videos) {
      result.videos = []
    }
    return result
  }
  return obj
}

export const usePropertyStore = create<PropertyStore>((set, get) => ({
  properties: [],
  loading: false,
  error: null,

  getPropertyById: (id: string) => {
    return get().properties.find(p => p.id === id)
  },

  getPublishedProperties: () => {
    return get().properties.filter(p => p.status === 'published')
  },

  fetchProperties: async () => {
    set({ loading: true, error: null });
    // No explicit status filter here — RLS decides what comes back: an
    // anonymous visitor only ever receives `published` rows, while an
    // authenticated admin session receives everything. Same query, two
    // audiences; see the migration's properties_* policies.
    const { data, error } = await supabase
      .from('properties')
      .select('*')
      .order('created_at', { ascending: false });

    if (error) {
      console.error('Error fetching properties:', error);
      set({ loading: false, error: error.message });
      return;
    }

    set({ properties: toCamelCase(data ?? []), loading: false });
  },

  addProperty: async (property) => {
    // id, property_code, created_at, and updated_at are all generated by
    // the database (see the migration) — the client never invents them.
    const { data, error } = await supabase
      .from('properties')
      .insert([toSnakeCase(property)])
      .select()
      .single();

    if (error) {
      console.error('Error adding property:', error)
      logToGoogleSheet({
        logType: 'ERROR',
        message: 'Failed to Add Property',
        details: { title: property.title, error: error.message },
      })
      throw error
    }

    const newProperty = toCamelCase(data) as Property

    logToGoogleSheet({
      logType: 'PROPERTY_ADD',
      message: `Property Added: ${newProperty.title}`,
      details: {
        id: newProperty.id,
        propertyCode: newProperty.propertyCode,
        title: newProperty.title,
        location: newProperty.location,
        price: newProperty.price,
        type: newProperty.type,
        status: newProperty.status,
      },
    })

    // Activity entry for the insert itself is written by a DB trigger
    // (covers admin- and website-sourced rows alike) — nothing to log here.
    set(state => ({ properties: [...state.properties, newProperty] }))
  },

  updateProperty: async (id, updates) => {
    const existing = get().properties.find(p => p.id === id);

    const { data, error } = await supabase
      .from('properties')
      .update(toSnakeCase(updates))
      .eq('id', id)
      .select()
      .single();

    if (error) {
      console.error('Error updating property:', error)
      logToGoogleSheet({
        logType: 'ERROR',
        message: 'Failed to Update Property',
        details: { id, updates, error: error.message },
      })
      throw error
    }

    const updated = toCamelCase(data) as Property

    logToGoogleSheet({
      logType: 'PROPERTY_UPDATE',
      message: `Property Updated: ID ${id}`,
      details: {
        id,
        title: updates.title || '',
        price: updates.price || '',
        location: updates.location || '',
        updates,
      },
    })

    const statusChanged = updates.status && existing && updates.status !== existing.status;
    const message = statusChanged
      ? `"${existing!.title}" marked ${updates.status}`
      : `Updated "${existing?.title || id}"`;

    set(state => ({
      properties: state.properties.map(p => p.id === id ? updated : p),
    }))
    useActivityStore.getState().log(message, 'property', id)
  },

  deleteProperty: async (id) => {
    const property = get().properties.find(p => p.id === id)

    if (property) {
      // Delete images from storage first
      for (const imageUrl of property.images) {
        try {
          const path = imageUrl.split('/properties/')[1]
          if (path) {
            await supabase.storage.from('properties').remove([path])
          }
        } catch (err) {
          console.error('Error deleting image:', err)
        }
      }

      // Delete uploaded videos from storage
      if (property.videos && property.videos.length > 0) {
        for (const videoUrl of property.videos) {
          try {
            const path = videoUrl.split('/properties/')[1]
            if (path) {
              await supabase.storage.from('properties').remove([path])
            }
          } catch (err) {
            console.error('Error deleting video:', err)
          }
        }
      }
    }

    const { error } = await supabase
      .from('properties')
      .delete()
      .eq('id', id)

    if (error) {
      console.error('Error deleting property:', error)
      logToGoogleSheet({
        logType: 'ERROR',
        message: 'Failed to Delete Property',
        details: { id, error: error.message },
      })
      throw error
    }

    logToGoogleSheet({
      logType: 'PROPERTY_DELETE',
      message: `Property Deleted: ${property?.title || id}`,
      details: {
        id,
        title: property?.title || '',
        location: property?.location || '',
      },
    })

    set(state => ({
      properties: state.properties.filter(p => p.id !== id),
    }))
    useActivityStore.getState().log(`Deleted "${property?.title || id}"`, 'property', id)
  }
}))
